#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# full paths from the repo root separated by newlines
MUST_NOT_CHANGE='package.json'

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

exec 1>&2

if git diff --cached --name-only $against |
   grep --quiet --line-regexp --fixed-strings "$MUST_NOT_CHANGE"
then
  echo "Commit will modify package.json or package-lock.json in the ./ folder!"
  echo "Do not commit until you fix this issue!"
  exit 1
else
  exit 0
fi
